#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=50
RESTART=99

PROG=/usr/bin/cloudflared

start_service()
{
    config_load 'cloudflared'
    config_get token config token

    if [ -z "$token" ]; then
        echo "No cloudflared tunnel token found!"
        return 1
    fi

    # fix the cf buffer issues
    sysctl -w net.core.rmem_max=2500000 &> /dev/null
    # Service details
    procd_open_instance
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param command "${PROG}" tunnel run --token $token
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-15} ${respawn_retry:-200}
    procd_set_param user
    procd_close_instance
}

stop_service()
{
    service_stop ${PROG}
}